name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build infrastructure
      run: |
        cd infrastructure
        npm install
        npm run build
        
    - name: Build backend
      run: |
        cd backend/lambda/video-processor
        npm install
        npm run build
        
    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build
        
    - name: Run tests
      run: npm test
      
    - name: Deploy to AWS (on main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        cd infrastructure
        npm run deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} 